class AuthUser < BaseModel
  skip_default_columns
  table :auth_user do
    primary_key id : Int32
    column password : String = "", allow_blank: true
    column last_login : Time?
    column is_superuser : Bool = false
    column username : String
    column first_name : String = "", allow_blank: true
    column last_name : String = "", allow_blank: true
    column email : String = "", allow_blank: true
    column is_staff : Bool = false
    column is_active : Bool = true
    column date_joined : Time, autogenerated: true
  end
end
