class CollectPoint < BaseModel
  skip_default_columns
  table :collect_points do
    primary_key id : UUID
    column created_at : Time, autogenerated: true
    # Djangoで生成したテーブルで大陸continentをcontientとtypoしてしまった
    # 不整合が生じると面倒なので、あえてカラム名をそのままにしておく
    column contient : String = "", allow_blank: true
    column island_group : String = "", allow_blank: true
    column island : String = "", allow_blank: true
    column country : String = "", allow_blank: true
    column state_provice : String = "", allow_blank: true
    column county : String = "", allow_blank: true
    column municipality : String = "", allow_blank: true
    column verbatim_locality : String = "", allow_blank: true
    column japanese_place_name : String = "", allow_blank: true
    column japanese_place_name_detail : String = "", allow_blank: true
    column coordinate_precision : Float64 = 0.0
    column location : PostGIS::Point2D
    column minimum_elevation : Float64 = 0.0
    column maximum_elevation : Float64 = 0.0
    column minimum_depth : Float64 = 0.0
    column maximum_depth : Float64 = 0.0
    column note : String = "", allow_blank: true
    column image1 : String?
    column image2 : String?
    column image3 : String?
    column image4 : String?
    column image5 : String?
    column user_id : Int32?
  end
end
