class SpecimenLabel < BaseModel
  skip_default_columns
  table :specimen_labels do
    primary_key id : UUID
    column created_at : Time, autogenerated: true
    column user_id : Int32?
    column name : String

    has_many label_specimens : SpecimenLabelLabelSpecimen

    data_label_flag : Bool = true
    coll_label_flag : Bool = true
    det_label_flag : Bool = true
    note_label_flag : Bool = true
  end
end
