class Taxon < BaseModel
  skip_default_columns
  table :all_taxa do
    primary_key id : UUID
    column created_at : Time, autogenerated: true
    # 以下、分類データのカラムをGBIFベースで定義
    # カラム項目はDarwin Core 1.2に概ね準拠
    # カラム名はDarwin Core 1.2をsnake_caseの表記に変更したもの
    # 名前がよりシンプルになるものは一部Darwin Core 最新版に準拠
    # 以下、コメント内ではDarwin CoreをDCと略記

    # 界
    column kingdom  : String = "", allow_blank: true
    # 門
    column phylum : String = "", allow_blank: true
    # 鋼 予約語と被るため_nameを付与
    column class_name : String = "", allow_blank: true
    # 目
    column order : String = "", allow_blank: true
    # 亜目(オリジナル)
    column suborder : String = "", allow_blank: true
    # 科
    column family : String = "", allow_blank: true
    # 亜科(オリジナル)
    column subfamily : String = "", allow_blank: true
    # 族(オリジナル)
    column tribe : String = "", allow_blank: true
    # 亜族(オリジナル)
    column subtribe : String = "", allow_blank: true
    # 属
    column genus : String = "", allow_blank: true
    # 亜属
    column subgenus : String = "", allow_blank: true
    # 種
    column species : String = "", allow_blank: true
    # 亜種
    column subspecies : String = "", allow_blank: true
    # 記載者
    column scientific_name_author : String = "", allow_blank: true
    # 記載年 DC最新版準拠
    column name_publishedin_year : Int32 = 0, allow_blank: true

    # 以上、GBIFベースでのカラム定義終了
    # 以下はオリジナルのカラム

    # 属移動カッコの有無
    column change_genus_brackets : Bool = false
    # 記載者不明角カッコの有無
    column unknown_author_brackets : Bool = false
    # 記載年不明角カッコの有無
    column unknown_name_publishedin_year_brackets : Bool = false
    # 記載実流通年
    column actual_dist_year : Int32 = 0
    # 和名
    column japanese_name : String = "", allow_blank: true
    # 分布
    column distribution : String = "", allow_blank: true
    # 備考
    column note : String = "", allow_blank: true

    # 画像
    column image1 : String?
    column image2 : String?
    column image3 : String?
    column image4 : String?
    column image5 : String?
  end
end
